-- MySQL Script generated by MySQL Workbench
-- Mon 01 May 2023 08:36:43 AM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Argentour
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Argentour
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Argentour` DEFAULT CHARACTER SET utf8 ;
USE `Argentour` ;

-- -----------------------------------------------------
-- Table `Argentour`.`Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Argentour`.`Provincia` (
  `idProvincia` INT NOT NULL AUTO_INCREMENT,
  `nombreProv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProvincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Argentour`.`Ciudad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Argentour`.`Ciudad` (
  `idCiudad` INT NOT NULL AUTO_INCREMENT,
  `nombreCiudad` VARCHAR(45) NOT NULL,
  `idProvincia` INT NOT NULL,
  PRIMARY KEY (`idCiudad`),
  INDEX `fk_Ciudad_1_idx` (`idProvincia` ASC) VISIBLE,
  CONSTRAINT `fk_Ciudad_1`
    FOREIGN KEY (`idProvincia`)
    REFERENCES `Argentour`.`Provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Argentour`.`Rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Argentour`.`Rol` (
  `idRol` INT NOT NULL AUTO_INCREMENT,
  `nombreRol` VARCHAR(25) NOT NULL,
  `descripcionRol` VARCHAR(99) NOT NULL,
  PRIMARY KEY (`idRol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Argentour`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Argentour`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `edad` INT NULL,
  `dni` INT NULL,
  `idProvincia` INT NOT NULL,
  `idCiudad` INT NOT NULL,
  `correo` VARCHAR(45) NULL,
  `tel` VARCHAR(45) NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `idRol` INT NOT NULL,
  PRIMARY KEY (`idUsuario`),
  INDEX `fk_Usuario_1_idx` (`idCiudad` ASC) VISIBLE,
  INDEX `fk_Usuario_2_idx` (`idRol` ASC) VISIBLE,
  INDEX `fk_Usuario_3_idx` (`idProvincia` ASC) VISIBLE,
  CONSTRAINT `fk_Usuario_1`
    FOREIGN KEY (`idCiudad`)
    REFERENCES `Argentour`.`Ciudad` (`idCiudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_2`
    FOREIGN KEY (`idRol`)
    REFERENCES `Argentour`.`Rol` (`idRol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_3`
    FOREIGN KEY (`idProvincia`)
    REFERENCES `Argentour`.`Provincia` (`idProvincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Argentour`.`Tipo Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Argentour`.`Tipo Producto` (
  `idTipoProducto` INT NOT NULL AUTO_INCREMENT,
  `nombreTipoP` VARCHAR(55) NOT NULL,
  PRIMARY KEY (`idTipoProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Argentour`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Argentour`.`Producto` (
  `idProducto` INT NOT NULL AUTO_INCREMENT,
  `nombreProducto` VARCHAR(45) NOT NULL,
  `imagenProducto` VARCHAR(95) NULL,
  `precio` DOUBLE NOT NULL,
  `descProducto` VARCHAR(45) NULL,
  `idTipoProducto` INT NULL,
  PRIMARY KEY (`idProducto`),
  INDEX `fk_Producto_1_idx` (`idTipoProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Producto_1`
    FOREIGN KEY (`idTipoProducto`)
    REFERENCES `Argentour`.`Tipo Producto` (`idTipoProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Argentour`.`Carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Argentour`.`Carrito` (
  `idCarrito` INT NOT NULL AUTO_INCREMENT,
  `subTotal` FLOAT NOT NULL,
  `idUsuario` INT NOT NULL,
  `idProducto` INT NULL,
  PRIMARY KEY (`idCarrito`),
  INDEX `fk_Carrito_1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_Carrito_2_idx` (`idProducto` ASC) VISIBLE,
  CONSTRAINT `fk_Carrito_1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Argentour`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Carrito_2`
    FOREIGN KEY (`idProducto`)
    REFERENCES `Argentour`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Argentour`.`Descuento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Argentour`.`Descuento` (
  `idDescuento` INT NOT NULL AUTO_INCREMENT,
  `nombreDesc` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDescuento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Argentour`.`Reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Argentour`.`Reserva` (
  `idReserva` INT NOT NULL,
  `idUsuario` INT NOT NULL,
  `idProducto` INT NULL,
  `cantidad` INT NULL,
  `fechaReserva` DATE NOT NULL,
  `idDescuento` INT NULL,
  `total` DOUBLE NOT NULL,
  PRIMARY KEY (`idReserva`),
  INDEX `fk_Reserva_1_idx` (`idUsuario` ASC) VISIBLE,
  INDEX `fk_Reserva_2_idx` (`idProducto` ASC) VISIBLE,
  INDEX `fk_Reserva_3_idx` (`idDescuento` ASC) VISIBLE,
  CONSTRAINT `fk_Reserva_1`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Argentour`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_2`
    FOREIGN KEY (`idProducto`)
    REFERENCES `Argentour`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reserva_3`
    FOREIGN KEY (`idDescuento`)
    REFERENCES `Argentour`.`Descuento` (`idDescuento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Argentour`.`MetodoPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Argentour`.`MetodoPago` (
  `idMetodoPago` INT NOT NULL AUTO_INCREMENT,
  `nombreMetodoP` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idMetodoPago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Argentour`.`Pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Argentour`.`Pago` (
  `idPago` INT NOT NULL AUTO_INCREMENT,
  `idReserva` INT NOT NULL,
  `idMetodoPago` INT NOT NULL,
  `fechaEmision` DATE NOT NULL,
  `monto` FLOAT NOT NULL,
  PRIMARY KEY (`idPago`),
  INDEX `fk_Pago_1_idx` (`idReserva` ASC) VISIBLE,
  INDEX `fk_Pago_2_idx` (`idMetodoPago` ASC) VISIBLE,
  CONSTRAINT `fk_Pago_1`
    FOREIGN KEY (`idReserva`)
    REFERENCES `Argentour`.`Reserva` (`idReserva`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pago_2`
    FOREIGN KEY (`idMetodoPago`)
    REFERENCES `Argentour`.`MetodoPago` (`idMetodoPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
