# Generated by Django 4.2.1 on 2023-06-09 23:09

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_Categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=55)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_Ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ciudad',
            },
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id_Descuento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Descuento',
                'verbose_name_plural': 'Descuentos',
                'db_table': 'descuento',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_Metodo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Metodo',
                'verbose_name_plural': 'Metodos',
                'db_table': 'metodo',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_Producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('imagen', models.CharField(blank=True, max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, default=2000, max_digits=10)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('cantidad', models.IntegerField(default=100)),
                ('id_Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArgentourApi.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_Provincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Provincias',
                'db_table': 'provincia',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('dni', models.IntegerField(blank=True, default=0)),
                ('tel', models.CharField(blank=True, max_length=45)),
                ('edad', models.IntegerField(blank=True, default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('id_Ciudad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArgentourApi.ciudad')),
                ('id_Provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArgentourApi.provincia')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_Reserva', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=0)),
                ('fecha_Reserva', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=2)),
                ('id_Descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArgentourApi.descuento')),
                ('id_Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArgentourApi.producto')),
                ('id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_Pago', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_Emision', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_Metodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArgentourApi.metodopago')),
                ('id_Reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArgentourApi.reserva')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='id_Provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArgentourApi.provincia'),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_Carrito', models.AutoField(primary_key=True, serialize=False)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('id_Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArgentourApi.producto')),
                ('id_Usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='email')),
            ],
            options={
                'verbose_name': 'Carrito',
                'verbose_name_plural': 'Carritos',
                'db_table': 'carrito',
            },
        ),
    ]
